# Generated by Django 5.0.6 on 2024-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.CharField(max_length=60)),
                ('Number', models.IntegerField(default=0)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField(default='')),
            ],
        ),
    ]
