# Generated by Django 5.0.6 on 2024-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='Message',
            field=models.TextField(default='empty'),
        ),
    ]
