# Generated by Django 5.0.6 on 2024-07-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_alter_contactmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='Number',
            field=models.IntegerField(default=10),
        ),
    ]
